# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  wallets_backend-postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"


volumes:
  postgres-db:
    driver: local

